LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := deezer

LOCAL_SRC_FILES := $(LOCAL_PATH)/$(TARGET_ARCH_ABI)/libdeezer.so
LOCAL_EXPORT_LDLIBS := $(LOCAL_PATH)/$(TARGET_ARCH_ABI)/libdeezer.so

include $(PREBUILT_SHARED_LIBRARY)
