LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := taglib

LOCAL_SRC_FILES := $(LOCAL_PATH)/$(TARGET_ARCH_ABI)/libs/libtaglib.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include
LOCAL_EXPORT_LDLIBS := $(LOCAL_PATH)/$(TARGET_ARCH_ABI)/libs/libtaglib.so

include $(PREBUILT_SHARED_LIBRARY)